import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "text-secondary": "#5C5C5C",
        "primary-container": "#0f4c81",
        "on-tertiary-fixed": "#2b1613",
        "on-primary-fixed-variant": "#07497d",
        "surface-tint": "#2d6197",
        "outline-variant": "#c2c7d1",
        "on-error": "#ffffff",
        secondary: "#934b19",
        "inverse-surface": "#313030",
        tertiary: "#462d2a",
        "on-secondary-fixed-variant": "#753401",
        "secondary-fixed": "#ffdbc9",
        "on-tertiary-container": "#d6b1ac",
        "on-primary-fixed": "#001c37",
        "surface-container-low": "#f6f3f2",
        "semantic-info": "#0277BD",
        "semantic-success": "#2E7D32",
        "semantic-error": "#C62828",
        "text-primary": "#1A1A1A",
        "on-tertiary-fixed-variant": "#5b403d",
        "on-surface-variant": "#42474f",
        outline: "#727780",
        "semantic-warning": "#F57F17",
        surface: "#fcf9f8",
        "surface-bright": "#fcf9f8",
        "secondary-container": "#ffa26a",
        "on-tertiary": "#ffffff",
        "on-surface": "#1c1b1b",
        primary: "#00355f",
        "surface-container-highest": "#e5e2e1",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#783603",
        background: "#fcf9f8",
        "inverse-on-surface": "#f3f0ef",
        "on-primary-container": "#8ebdf9",
        "tertiary-fixed-dim": "#e4beb9",
        error: "#ba1a1a",
        "tertiary-fixed": "#ffdad5",
        "on-secondary-fixed": "#321200",
        "surface-variant": "#e5e2e1",
        "surface-dim": "#dcd9d9",
        "surface-base": "#FDFDFD",
        "inverse-primary": "#a0c9ff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#ffb68c",
        "error-container": "#ffdad6",
        "surface-container": "#f0eded",
        "primary-fixed-dim": "#a0c9ff",
        "surface-elevated": "#F4F5F7",
        "on-error-container": "#93000a",
        "tertiary-container": "#5f4340",
        "surface-container-high": "#eae7e7",
        "on-primary": "#ffffff",
        "on-background": "#1c1b1b",
        "primary-fixed": "#d2e4ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xl: "48px",
        lg: "32px",
        sm: "16px",
        xs: "12px",
        "3xs": "4px",
        md: "24px",
        "2xs": "8px",
      },
      fontFamily: {
        h1: ["var(--font-work-sans)", "system-ui", "sans-serif"],
        "body-base": ["var(--font-work-sans)", "system-ui", "sans-serif"],
        label: ["var(--font-work-sans)", "system-ui", "sans-serif"],
        "body-large": ["var(--font-work-sans)", "system-ui", "sans-serif"],
        caption: ["var(--font-work-sans)", "system-ui", "sans-serif"],
        h2: ["var(--font-work-sans)", "system-ui", "sans-serif"],
        display: ["var(--font-inter)", "system-ui", "sans-serif"],
        tabular: ["var(--font-ibm-plex-sans)", "ui-monospace", "monospace"],
      },
      fontSize: {
        h1: ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-base": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        label: ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-large": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        caption: ["11px", { lineHeight: "16px", fontWeight: "400" }],
        h2: ["20px", { lineHeight: "28px", fontWeight: "500" }],
        display: ["32px", { lineHeight: "1.2", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;

